name = "Hugo Initio"
license = "MIT"
licenselink = "https://github.com/coreer/hugo-initio/blob/master/LICENSE.md"
description = ""
homepage = "https://github.com/coreer/hugo-initio"
tags = ["blog","responsive","personal","google analytics","portfolio","disqus","bootstrap","font awesome","projects","creative","landing page","product","white","share this"]
features = ["blog","responsive","personal","google analytics","portfolio","disqus","bootstrap","font awesome","projects","creative","landing page","product","white","share this"]
min_version = "0.1"

[author]
  homepage = "https://github.com/coreer/hugo-initio/"

[original]
  name = "Initio"
  author = "Sergey Pozhilov"
  homepage = "http://www.gettemplate.com/info/initio/"
  repo = "https://github.com/pozh/Initio"
